import os

DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")
NASA_KEY = os.getenv("NASA_KEY")

SP_CLIENT_ID = os.getenv("SP_CLIENT_ID")
SP_CLIENT_SECRET = os.getenv("SP_CLIENT_SECRET")
SP_REFRESH_TOKEN = os.getenv("SP_REFRESH_TOKEN")

WOLFRAM_APP_ID = os.getenv("WOLFRAM_API")
DATABASE_URL = os.getenv("DATABASE_URL")